# Generated by Django 4.1.1 on 2022-09-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupon_active_remove_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=10),
        ),
    ]
