# Generated by Django 4.1.1 on 2022-09-25 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_alter_coupon_coupon_code_alter_coupon_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
