# Generated by Django 4.1.1 on 2022-09-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_post_title_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
