# Generated by Django 4.1.1 on 2022-10-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_remove_post_sku_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, null=True)),
                ('body', models.TextField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, null=True)),
                ('abstract', models.CharField(blank=True, help_text='get the first 54 text', max_length=54, null=True)),
                ('views', models.PositiveIntegerField(default=0, null=True)),
                ('likes', models.PositiveIntegerField(default=0, null=True)),
                ('topped', models.BooleanField(default=False, null=True)),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
