# Generated by Django 4.1.1 on 2022-11-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_alter_event_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.CharField(blank=True, help_text='Write a post excerpt within 200 characters', max_length=100, null=True),
        ),
    ]
