# Generated by Django 4.1.1 on 2022-11-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_event_image_alter_event_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
